[versions]
agp = "8.3.0"
junitVersion = "1.2.1"

appcompat = "1.6.1"
material = "1.9.0"
glide = "4.15.1"
glideCompiler = "4.15.1"
junit = "4.13.2"
extJunit = "1.1.5"
espressoCore = "3.5.1"


[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glideCompiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideCompiler" }
junit = { module = "junit:junit", version.ref = "junit" }
extJunit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }


[plugins]
androidApplication = { id = "com.android.application", version = "8.0.2" }

